In [45]:
import numpy as np
import pandas as pd

from importlib import reload
import netanalytics.inference; reload(netanalytics.inference)
from netanalytics.inference import mutual_rank_graph

In [50]:
X = pd.read_csv("/Users/veronica/Dropbox (DIBRIS)/project_UCL/data/BRCA_gene_expression_subset.csv", index_col=0, header=None)

In [52]:
X

1          2         3         4         5         6         7     \
0                                                                             
0     4.087463  14.778026  5.523562  1.000000  0.000000  0.000000  0.000000   
1     5.857981  15.538098  6.700440  4.247928  2.584963  0.000000  0.000000   
2     4.087463  14.798877  5.169925  3.700440  2.584963  1.584963  0.000000   
3     4.754888  15.992983  6.375039  4.169925  0.000000  3.906891  0.000000   
4     3.000000  13.704984  6.768184  3.700440  1.000000  0.000000  0.000000   
5     5.044394  16.205373  6.658211  5.129283  2.584963  1.584963  0.000000   
6     4.392317  14.779206  5.727920  2.321928  2.000000  0.000000  0.000000   
7     6.459432  15.408164  6.066089  3.906891  0.000000  1.584963  0.000000   
8     5.209453  15.403212  6.266787  1.584963  2.807355  5.930737  1.000000   
9     4.754888  13.776947  4.857981  1.584963  0.000000  0.000000  0.000000   
10    4.700440  17.988357  6.918863  6.584963  0.000000  3.906891  0.000000   
11    4.643856  16.765713  5.357552  4.087463  2.321928  4.169925  0.000000   
12    5.672425  14.367005  6.569856  3.321928  0.000000  0.000000  0.000000   
13    4.459432  13.529309  4.954196  6.169925  3.169925  5.930737  6.303781   
14    6.108524  15.107626  9.407268  3.169925  1.584963  2.000000  0.000000   
15    6.169925  15.502956  5.321928  1.000000  2.000000  0.000000  0.000000   
16    2.584963  13.038576  5.491853  0.000000  0.000000  0.000000  0.000000   
17    5.247928  15.903035  6.189825  3.906891  2.584963  3.459432  0.000000   
18    4.857981  14.448439  5.129283  4.584963  1.584963  0.000000  0.000000   
19    5.000000  11.363587  3.000000  0.000000  0.000000  2.321928  0.000000   
20    4.321928  14.653853  7.266787  2.807355  1.584963  0.000000  0.000000   
21    4.392317  16.203138  6.686501  3.459432  0.000000  2.584963  0.000000   
22    5.426265  14.756608  5.906891  2.000000  2.584963  0.000000  0.000000   
23    5.357552  13.349005  7.108524  2.584963  4.523562  0.000000  0.000000   
24    5.087463  14.000264  5.129283  4.000000  0.000000  0.000000  0.000000   
25    5.491853  14.314583  5.672425  1.584963  1.584963  0.000000  0.000000   
26    6.357552  14.729461  5.643856  0.000000  1.000000  8.044394  9.505812   
27    5.930737  15.576898  5.882643  4.321928  1.584963  4.954196  0.000000   
28    5.129283  15.291243  6.882643  0.000000  2.807355  3.000000  2.000000   
29    5.285402  15.014151  7.055282  5.392317  0.000000  1.000000  0.000000   
...        ...        ...       ...       ...       ...       ...       ...   
1016  5.169925  14.842449  5.977280  2.584963  0.000000  0.000000  1.000000   
1017  4.584963  15.622795  6.768184  2.807355  0.000000  0.000000  0.000000   
1018  4.392317  16.006348  5.882643  3.000000  2.000000  1.584963  0.000000   
1019  4.321928  15.270770  6.894818  3.000000  0.000000  0.000000  0.000000   
1020  2.321928  13.159871  5.643856  3.169925  0.000000  2.807355  0.000000   
1021  4.954196  15.047976  6.918863  2.321928  0.000000  0.000000  0.000000   
1022  5.087463  15.478959  6.321928  2.321928  1.584963  0.000000  0.000000   
1023  5.357552  16.019026  7.219169  3.700440  0.000000  1.584963  1.584963   
1024  5.491853  15.446857  5.614710  5.882643  0.000000  1.584963  1.584963   
1025  6.022368  13.399945  7.515700  2.807355  2.807355  0.000000  0.000000   
1026  4.169925  15.122545  5.727920  3.459432  2.321928  1.000000  0.000000   
1027  4.954196  15.078943  5.321928  5.357552  0.000000  0.000000  0.000000   
1028  5.491853  15.162155  5.209453  2.807355  0.000000  5.807355  0.000000   
1029  4.906891  14.060780  5.129283  3.000000  1.000000  3.807355  0.000000   
1030  4.643856  14.350870  4.857981  1.000000  0.000000  3.584963  0.000000   
1031  4.523562  13.498475  6.000000  2.807355  0.000000  2.807355  1.000000   
1032  3.000000  14.702443  5.285402  3.584963  0.000000  0.000000  0.000000   
1033  6.149747  14.850724  6.022368  4.643856  1.000000  1.0

In [53]:
res = mutual_rank_graph(X)

/Users/veronica/miniconda3/envs/py36/lib/python3.6/site-packages/scipy-1.1.0-py3.6-macosx-10.7-x86_64.egg/scipy/stats/stats.py:3010: RuntimeWarning: invalid value encountered in double_scalars
  r = r_num / r_den


KeyboardInterrupt: 

In [8]:
prova = np.random.rand(10)

In [9]:
np.sort(prova)

array([0.00097942, 0.04596869, 0.23838322, 0.23871931, 0.28307024,
       0.32230905, 0.42804539, 0.68203174, 0.76481762, 0.83713463])

In [10]:
np.argsort(prova)

array([9, 4, 3, 5, 2, 8, 6, 0, 1, 7])

In [11]:
prova[np.argsort(prova)]

array([0.00097942, 0.04596869, 0.23838322, 0.23871931, 0.28307024,
       0.32230905, 0.42804539, 0.68203174, 0.76481762, 0.83713463])

In [24]:
i = np.arange(1, 11)
i[np.argsort(prova)[::-1]]

array([ 8,  2,  1,  7,  9,  3,  6,  4,  5, 10])